-- =====================================================================
-- OPP WEB — SCHEMA COMPLETO (rodar uma vez no SQL Editor do Supabase)
-- Desenvolvimento de Produto (Design) — Chilli Beans
-- Padrão herdado do SysPlan Web: Auth + RLS + permissões por tela +
-- auditoria campo a campo por trigger.
-- =====================================================================

-- =====================================================================
-- USUÁRIOS, PERFIS E PERMISSÕES
-- =====================================================================

create type perfil_usuario as enum ('admin', 'usuario');

create table usuarios (
  id uuid primary key references auth.users (id) on delete cascade,
  nome text not null default '',
  email text not null unique,
  perfil perfil_usuario not null default 'usuario',
  bloqueado boolean not null default false,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- Catálogo de telas/módulos do sistema (permissões por tela)
create table telas (
  codigo text primary key,
  nome text not null,
  grupo text not null default 'Sistema',
  ordem integer not null default 0
);

create table permissoes (
  usuario_id uuid not null references usuarios (id) on delete cascade,
  tela_codigo text not null references telas (codigo) on delete cascade,
  pode_visualizar boolean not null default true,
  pode_editar boolean not null default false,
  primary key (usuario_id, tela_codigo)
);

-- Log de auditoria (mesmo modelo do SysPlan)
create table log_transacoes (
  cd_transacao bigint generated by default as identity primary key,
  usuario_id uuid references usuarios (id),
  transacao text not null,
  cd_item_transacao integer default 0,
  dt_transacao timestamptz not null default now(),
  info_anterior text,
  info_atual text,
  campo_editado text
);

create index idx_log_transacoes_item on log_transacoes (cd_item_transacao);
create index idx_log_transacoes_dt on log_transacoes (dt_transacao desc);
create index idx_log_transacoes_usuario on log_transacoes (usuario_id);
create index idx_log_transacoes_transacao on log_transacoes (transacao);

-- =====================================================================
-- PRMs — ESPELHO DO SYSPLAN WEB (somente leitura)
-- Toda alteração é feita exclusivamente no SysPlan; o OPP apenas consome.
-- As tabelas são atualizadas pelo script `npm run sync:prm` (service_role).
-- =====================================================================

-- Espelho de prm_grupo (ids preservados do SysPlan; GERAL = cd_grupo 2)
create table prm_grupo (
  cd_grupo integer primary key,
  dc_grupo text not null unique
);

-- Espelho de prm_combos (subgrupo, atributos, canal, griffe... por grupo)
create table prm_combos (
  cd_combo integer primary key,
  cd_grupo integer not null references prm_grupo (cd_grupo),
  dc_tipo_combo text not null,
  dc_combo text not null
);
create index idx_prm_combos_tipo on prm_combos (cd_grupo, dc_tipo_combo);

-- Espelho de prm_grupo_planejamento
create table prm_grupo_planejamento (
  dc_grupo text not null,
  dc_subgrupo text not null,
  dc_sexo text not null,
  dc_formato text not null,
  dc_grupo_planejamento text,
  primary key (dc_grupo, dc_subgrupo, dc_sexo, dc_formato)
);

-- =====================================================================
-- DEMANDAS (tabela larga: classificação + datas de todas as etapas)
-- =====================================================================

create table demandas (
  cd_demanda integer generated by default as identity primary key,

  -- Classificação
  canal text,
  griffe text,
  grupo text,
  subgrupo text,
  fornecedor text,
  grupo_planejamento text,
  sexo text,
  atributo_1 text,
  atributo_2 text,
  preco_varejo numeric(10,2),
  lente_antecipada boolean not null default false,

  -- Códigos
  cod_1 text,
  cod_2 text,
  cod_3_licenca text,
  sku text,
  data_compra date,

  -- Controle (exclusão é lógica via status = 'EXCLUIDO')
  status text not null default 'ATIVO' check (status in ('ATIVO','ENCERRADO','CANCELADO','EXCLUIDO')),
  etapa_atual text not null default 'MIX',
  ficha_url text,

  -- MIX
  recebimento_mix date,
  selecao_amostras date,
  aprovacao_mix date,

  -- DESENVOLVIMENTO
  desenvolvimento date,
  aprovacao_desenvolvimento date,
  envio_desenvolvimento date,

  -- DESENHO TÉCNICO
  recebimento_dt date,
  aprovacao_dt date,
  comentarios_dt text,

  -- PROTÓTIPO
  solicitacao_prototipo date,
  recebimento_prototipo date,
  aprovacao_prototipo date,
  aprovacao_licenca_proto date,
  comentarios_proto text,

  -- COLOR SAMPLE
  solicitacao_cs date,
  recebimento_foto_cs date,
  recebimento_fisico_cs date,
  aprovacao_cs date,
  aprovacao_licenca_cs date,
  comentarios_cs text,

  -- SET FINAL
  solicitacao_sf date,
  recebimento_foto_sf date,
  recebimento_fisico_sf date,
  aprovacao_licenca_sf date,
  comentarios_sf text,

  -- LICENÇA GERAL
  comentarios_licenca text,

  -- Auditoria
  criado_por uuid references usuarios (id),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index idx_demandas_status on demandas (status);
create index idx_demandas_etapa on demandas (etapa_atual);
create index idx_demandas_griffe on demandas (griffe);
create index idx_demandas_canal on demandas (canal);
create index idx_demandas_fornecedor on demandas (fornecedor);
create index idx_demandas_criado on demandas (criado_em desc);

-- =====================================================================
-- ARQUIVOS (anexos por demanda — fichas, desenhos, protótipos...)
-- =====================================================================

create table arquivos (
  cd_arquivo integer generated by default as identity primary key,
  cd_demanda integer not null references demandas (cd_demanda) on delete cascade,
  tipo text not null check (tipo in (
    'FICHA','DESENHO_TECNICO','PROTOTIPO','COLOR_SAMPLE','SET_FINAL'
  )),
  url text not null,
  nome_original text,
  versao integer not null default 1,
  criado_por uuid references usuarios (id),
  criado_em timestamptz not null default now()
);

create index idx_arquivos_demanda on arquivos (cd_demanda);

-- =====================================================================
-- FUNÇÕES DE APOIO (Auth / permissões / log)
-- =====================================================================

create or replace function fn_usuario_atual() returns uuid
language sql stable security definer set search_path = public as $$
  select id from usuarios where id = auth.uid() and not bloqueado;
$$;

create or replace function fn_is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from usuarios where id = auth.uid() and perfil = 'admin' and not bloqueado
  );
$$;

create or replace function fn_tem_permissao(p_tela text, p_editar boolean default false)
returns boolean language sql stable security definer set search_path = public as $$
  select fn_is_admin() or exists (
    select 1 from permissoes p
    join usuarios u on u.id = p.usuario_id
    where p.usuario_id = auth.uid()
      and p.tela_codigo = p_tela
      and not u.bloqueado
      and p.pode_visualizar
      and (not p_editar or p.pode_editar)
  );
$$;

create or replace function fn_registra_transacao(
  p_transacao text, p_item integer default 0,
  p_info_anterior text default '', p_info_atual text default '', p_campo text default ''
) returns void language sql security definer set search_path = public as $$
  insert into log_transacoes (usuario_id, transacao, cd_item_transacao, info_anterior, info_atual, campo_editado)
  values (auth.uid(), p_transacao, coalesce(p_item, 0), p_info_anterior, p_info_atual, p_campo);
$$;

-- =====================================================================
-- REGRA DE NEGÓCIO: cálculo da etapa atual
-- (portada do etapa-calculator do sistema anterior — a data de aprovação
--  mais avançada preenchida define a etapa)
-- =====================================================================

create or replace function fn_calcula_etapa(d demandas) returns text
language sql immutable as $$
  select case
    when d.status = 'ENCERRADO' then 'ENCERRADA'
    when d.aprovacao_licenca_sf is not null or d.recebimento_fisico_sf is not null then 'SET_FINAL'
    when d.aprovacao_cs is not null then 'SET_FINAL'
    when d.aprovacao_prototipo is not null then 'COLOR_SAMPLE'
    when d.aprovacao_dt is not null then 'PROTOTIPO'
    when d.aprovacao_desenvolvimento is not null then 'DESENHO_TECNICO'
    when d.aprovacao_mix is not null then 'DESENVOLVIMENTO'
    else 'MIX'
  end;
$$;

-- =====================================================================
-- TRIGGERS
-- =====================================================================

-- Campos calculados mantidos pelo banco (etapa atual + atualizado_em)
create or replace function trg_calcula_demandas() returns trigger
language plpgsql as $$
begin
  new.etapa_atual := fn_calcula_etapa(new);
  new.atualizado_em := now();
  if tg_op = 'INSERT' and new.criado_por is null then
    new.criado_por := auth.uid();
  end if;
  return new;
end;
$$;

create trigger calcula_demandas
  before insert or update on demandas
  for each row execute function trg_calcula_demandas();

-- Auditoria campo a campo (gravações de serviço, sem usuário, não geram log)
create or replace function trg_audita_demandas() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_col text;
  v_old text;
  v_new text;
begin
  if auth.uid() is null then
    return new;
  end if;
  if tg_op = 'INSERT' then
    insert into log_transacoes (usuario_id, transacao, cd_item_transacao)
    values (auth.uid(), 'EdicaoDemanda - Criacao', new.cd_demanda);
    return new;
  end if;
  for v_col in
    select column_name from information_schema.columns
    where table_schema = 'public' and table_name = 'demandas'
      and column_name not in ('atualizado_em', 'criado_em', 'criado_por', 'etapa_atual')
  loop
    execute format('select ($1).%I::text, ($2).%I::text', v_col, v_col) into v_old, v_new using old, new;
    if v_old is distinct from v_new then
      insert into log_transacoes (usuario_id, transacao, cd_item_transacao, info_anterior, info_atual, campo_editado)
      values (auth.uid(), 'EdicaoDemanda - Alteracao', new.cd_demanda, coalesce(v_old, ''), coalesce(v_new, ''), v_col);
    end if;
  end loop;
  return new;
end;
$$;

create trigger audita_demandas
  after insert or update on demandas
  for each row execute function trg_audita_demandas();

-- Perfil criado automaticamente ao registrar usuário no Auth.
-- Novos usuários SEMPRE nascem como 'usuario' — promoção a admin
-- só por um administrador na tela de usuários.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.usuarios (id, email, nome, perfil)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'nome', split_part(new.email, '@', 1)),
    'usuario'::perfil_usuario
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- =====================================================================
-- ROW LEVEL SECURITY
-- =====================================================================

alter table usuarios enable row level security;
alter table telas enable row level security;
alter table permissoes enable row level security;
alter table log_transacoes enable row level security;
alter table prm_grupo enable row level security;
alter table prm_combos enable row level security;
alter table prm_grupo_planejamento enable row level security;
alter table demandas enable row level security;
alter table arquivos enable row level security;

-- Usuários / permissões / telas
create policy usuarios_select on usuarios for select to authenticated using (true);
create policy usuarios_admin_all on usuarios for all to authenticated
  using (fn_is_admin()) with check (fn_is_admin());

create policy telas_select on telas for select to authenticated using (true);
create policy telas_admin on telas for all to authenticated
  using (fn_is_admin()) with check (fn_is_admin());

create policy permissoes_select_propria on permissoes for select to authenticated
  using (usuario_id = auth.uid() or fn_is_admin());
create policy permissoes_admin on permissoes for all to authenticated
  using (fn_is_admin()) with check (fn_is_admin());

-- Logs: leitura restrita à tela admin_logs; escrita via funções security definer
create policy log_admin_select on log_transacoes for select to authenticated
  using (fn_tem_permissao('admin_logs'));

-- PRMs espelhados: somente leitura para autenticados. NÃO há política de
-- escrita — nem admin altera pelo app; apenas o service_role (sync) grava.
create policy prm_grupo_sel on prm_grupo for select to authenticated using (true);
create policy prm_combos_sel on prm_combos for select to authenticated using (true);
create policy prm_gp_sel on prm_grupo_planejamento for select to authenticated using (true);

-- Demandas: leitura/escrita conforme permissão da tela
create policy demandas_sel on demandas for select to authenticated
  using (fn_tem_permissao('lista_demandas'));
create policy demandas_ins on demandas for insert to authenticated
  with check (fn_tem_permissao('lista_demandas', true));
create policy demandas_upd on demandas for update to authenticated
  using (fn_tem_permissao('lista_demandas', true));
-- Exclusão física não permitida (exclusão é lógica via status = 'EXCLUIDO')

create policy arquivos_sel on arquivos for select to authenticated
  using (fn_tem_permissao('lista_demandas'));
create policy arquivos_all on arquivos for all to authenticated
  using (fn_tem_permissao('lista_demandas', true))
  with check (fn_tem_permissao('lista_demandas', true));

-- =====================================================================
-- SEEDS
-- =====================================================================

insert into telas (codigo, nome, grupo, ordem) values
  ('lista_demandas',   'Lista de Demandas',     'Demandas',      10),
  ('admin_usuarios',   'Usuários',              'Administração', 90),
  ('admin_permissoes', 'Permissões',            'Administração', 91),
  ('admin_parametros', 'Parâmetros (SysPlan)',  'Administração', 92),
  ('admin_logs',       'Logs',                  'Administração', 93)
on conflict (codigo) do nothing;

-- Os PRMs (grupos, combos, grupo planejamento) são carregados do SysPlan
-- com `npm run sync:prm` — não há seed local.

-- =====================================================================
-- ADMIN INICIAL
-- 1. Crie o usuário em Authentication → Users (ou pela tela de cadastro).
-- 2. Promova a admin:
--    update usuarios set perfil = 'admin' where email = 'seu-email@chillibeans.com.br';
-- =====================================================================
